# Generated by Django 4.2.9 on 2024-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='predicted_outcome',
            field=models.CharField(default='Something gone wrong', max_length=255),
        ),
    ]
